/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import Classes.*;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author lulves
 */
public final class formPrincipal extends javax.swing.JFrame {
    protected static ArrayList<Curso> listaCursos = new ArrayList();
    protected static ArrayList<Aluno> listaAlunos = new ArrayList();
    public static ArrayList <Professor> listaProfessores = new ArrayList();
    public static ArrayList <Disciplina> listaDisciplinas = new ArrayList();
    public static ArrayList <Turma> listaTurmas = new ArrayList();
    public static ArrayList <Matricula> listaMatriculas = new ArrayList();
    /**
     * Creates new form MaisUmaTentativaDeIntefacePrincipal
     */
    public formPrincipal() {
        initComponents();
        diretoNoCodigo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaPrincipal = new javax.swing.JDesktopPane() {
            private Image image;
            {
                try {
                    image = ImageIO.read(new File(System.getProperty("user.dir")+"/src/img/logoAtt.jpeg").getCanonicalFile());;
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };
        btnCadAluno = new javax.swing.JButton();
        btnCadProfessor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCadTurma = new javax.swing.JButton();
        btnMatricula = new javax.swing.JButton();
        btnCadCurso = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnCadDisciplina = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        menuSecCad = new javax.swing.JMenu();
        itemMenuCadAluno = new javax.swing.JMenuItem();
        itemMenuCadProfessor = new javax.swing.JMenuItem();
        itemMenuCadCurso = new javax.swing.JMenuItem();
        itemMenuCadTurma = new javax.swing.JMenuItem();
        itemMenuCadDiscilina = new javax.swing.JMenuItem();
        menuSecMatriculas = new javax.swing.JMenu();
        itemMenuMatrAluno = new javax.swing.JMenuItem();
        menuSecAbout = new javax.swing.JMenu();
        menuSecSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Área Principal de Gerenciamento de Cadastros - LPOO");

        AreaPrincipal.setPreferredSize(new java.awt.Dimension(800, 660));

        btnCadAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeAreaP/1496181148_Student-3.png"))); // NOI18N
        btnCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadAlunoActionPerformed(evt);
            }
        });

        btnCadProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeAreaP/essa.png"))); // NOI18N
        btnCadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadProfessorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    Cadastro Professor");

        btnCadTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeAreaP/turma.png"))); // NOI18N
        btnCadTurma.setText("Turma");
        btnCadTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadTurmaActionPerformed(evt);
            }
        });

        btnMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeAreaP/essaaquiii.png"))); // NOI18N
        btnMatricula.setText("Matricula");
        btnMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatriculaActionPerformed(evt);
            }
        });

        btnCadCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeAreaP/morri.png"))); // NOI18N
        btnCadCurso.setText("Disciplina");
        btnCadCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCursoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("      Cadastro Turma");

        btnCadDisciplina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconeAreaP/ESSAA.png"))); // NOI18N
        btnCadDisciplina.setText("Curso");
        btnCadDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadDisciplinaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("      Cadastro Aluno");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("   Cadastro Disciplina");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("      Cadastro Curso");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("    Matricular Aluno");

        AreaPrincipal.setLayer(btnCadAluno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AreaPrincipal.setLayer(btnCadProfessor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AreaPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AreaPrincipal.setLayer(btnCadTurma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AreaPrincipal.setLayer(btnMatricula, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AreaPrincipal.setLayer(btnCadCurso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AreaPrincipal.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AreaPrincipal.setLayer(btnCadDisciplina, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AreaPrincipal.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AreaPrincipal.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AreaPrincipal.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AreaPrincipal.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout AreaPrincipalLayout = new javax.swing.GroupLayout(AreaPrincipal);
        AreaPrincipal.setLayout(AreaPrincipalLayout);
        AreaPrincipalLayout.setHorizontalGroup(
            AreaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AreaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AreaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AreaPrincipalLayout.createSequentialGroup()
                        .addGap(502, 502, 502)
                        .addGroup(AreaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreaPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(AreaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadTurma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadDisciplina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        AreaPrincipalLayout.setVerticalGroup(
            AreaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AreaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AreaPrincipalLayout.createSequentialGroup()
                        .addComponent(btnCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(btnCadDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AreaPrincipalLayout.createSequentialGroup()
                        .addComponent(btnCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        menuSecCad.setBorder(null);
        menuSecCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesMenu/cadastroP.png"))); // NOI18N
        menuSecCad.setText("<html> <body> <b> <font face=\"verdana\"> CADASTROS </font> </b>  </body> </html>");

        itemMenuCadAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        itemMenuCadAluno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        itemMenuCadAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesMenu/aluno.png"))); // NOI18N
        itemMenuCadAluno.setText("Cadastro de Alunos");
        itemMenuCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadAlunoActionPerformed(evt);
            }
        });
        menuSecCad.add(itemMenuCadAluno);

        itemMenuCadProfessor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        itemMenuCadProfessor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        itemMenuCadProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesMenu/professor.png"))); // NOI18N
        itemMenuCadProfessor.setText("Cadastro de Professores");
        itemMenuCadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadProfessorActionPerformed(evt);
            }
        });
        menuSecCad.add(itemMenuCadProfessor);

        itemMenuCadCurso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        itemMenuCadCurso.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        itemMenuCadCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesMenu/curso.png"))); // NOI18N
        itemMenuCadCurso.setText("Cadastro de Cursos");
        itemMenuCadCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadCursoActionPerformed(evt);
            }
        });
        menuSecCad.add(itemMenuCadCurso);

        itemMenuCadTurma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        itemMenuCadTurma.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        itemMenuCadTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesMenu/turma.png"))); // NOI18N
        itemMenuCadTurma.setText("Cadastro de Turmas");
        itemMenuCadTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadTurmaActionPerformed(evt);
            }
        });
        menuSecCad.add(itemMenuCadTurma);

        itemMenuCadDiscilina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        itemMenuCadDiscilina.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        itemMenuCadDiscilina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesMenu/disciplina.png"))); // NOI18N
        itemMenuCadDiscilina.setText("Cadastro de Disciplinas");
        itemMenuCadDiscilina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadDiscilinaActionPerformed(evt);
            }
        });
        menuSecCad.add(itemMenuCadDiscilina);

        menuPrincipal.add(menuSecCad);

        menuSecMatriculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesMenu/matriculaP.png"))); // NOI18N
        menuSecMatriculas.setText("<html> <body> <b> <font face=\"verdana\"> MATRÍCULAS </font> </b>  </body> </html>");

        itemMenuMatrAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itemMenuMatrAluno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        itemMenuMatrAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesMenu/matricula.png"))); // NOI18N
        itemMenuMatrAluno.setText("Matricular Aluno em turmas ");
        itemMenuMatrAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuMatrAlunoActionPerformed(evt);
            }
        });
        menuSecMatriculas.add(itemMenuMatrAluno);

        menuPrincipal.add(menuSecMatriculas);

        menuSecAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesMenu/Information-32 (1).png"))); // NOI18N
        menuSecAbout.setText("<html> <body> <b> <font face=\"verdana\">SOBRE </font> </b>  </body> </html>");
        menuSecAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSecAboutMouseClicked(evt);
            }
        });
        menuPrincipal.add(menuSecAbout);

        menuSecSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesMenu/off.png"))); // NOI18N
        menuSecSair.setText("<html> <body> <b> <font face=\"verdana\"> SAIR </font> </b>  </body> </html>");
        menuSecSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSecSairMouseClicked(evt);
            }
        });
        menuPrincipal.add(menuSecSair);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadAlunoActionPerformed
        chamarTela(1);
    }//GEN-LAST:event_btnCadAlunoActionPerformed

    private void btnCadTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadTurmaActionPerformed
        chamarTela(5);
    }//GEN-LAST:event_btnCadTurmaActionPerformed

    private void btnCadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadProfessorActionPerformed
        chamarTela(3);
    }//GEN-LAST:event_btnCadProfessorActionPerformed

    private void btnMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatriculaActionPerformed
        chamarTela(4);
    }//GEN-LAST:event_btnMatriculaActionPerformed

    private void btnCadCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCursoActionPerformed
        chamarTela(2);
    }//GEN-LAST:event_btnCadCursoActionPerformed

    private void btnCadDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadDisciplinaActionPerformed
        chamarTela(6);
    }//GEN-LAST:event_btnCadDisciplinaActionPerformed

    private void itemMenuCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadAlunoActionPerformed
        chamarTela(1);
    }//GEN-LAST:event_itemMenuCadAlunoActionPerformed

    private void itemMenuCadCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadCursoActionPerformed
        chamarTela(2);
    }//GEN-LAST:event_itemMenuCadCursoActionPerformed

    private void itemMenuCadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadProfessorActionPerformed
        chamarTela(3);
    }//GEN-LAST:event_itemMenuCadProfessorActionPerformed

    private void itemMenuCadTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadTurmaActionPerformed
        chamarTela(5);
    }//GEN-LAST:event_itemMenuCadTurmaActionPerformed

    private void itemMenuCadDiscilinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadDiscilinaActionPerformed
        chamarTela(6);
    }//GEN-LAST:event_itemMenuCadDiscilinaActionPerformed

    private void itemMenuMatrAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuMatrAlunoActionPerformed
        chamarTela(4);
    }//GEN-LAST:event_itemMenuMatrAlunoActionPerformed

    private void menuSecSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSecSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuSecSairMouseClicked

    private void menuSecAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSecAboutMouseClicked
        JOptionPane.showMessageDialog(null, "Desenvolvido por Luara A. e Muriel S.\n Composição de nota G2\n Professora Msc. Madianita B. Marioti","Desevolvido por: ",JOptionPane.ERROR_MESSAGE,new ImageIcon(System.getProperty("user.dir")+"/src/img/iconesBotoes/iconesMicro/about.jpg"));
    }//GEN-LAST:event_menuSecAboutMouseClicked
    
    public void chamarTela(int opcao){
        switch (opcao){
            case 1:
                formCadAluno telaCadAluno = new formCadAluno();
                AreaPrincipal.add(telaCadAluno);
                telaCadAluno.setVisible(true);
                break;
            case 2:
                formCadCurso telaCadCurso = new formCadCurso();
                AreaPrincipal.add(telaCadCurso);
                telaCadCurso.setVisible(true);
                break;
            case 3:
                formCadProfessor telaCadProf = new formCadProfessor();
                AreaPrincipal.add(telaCadProf);
                telaCadProf.setVisible(true);
                break; 
            case 4:
                formMatricula telaMatricula = new formMatricula();
                AreaPrincipal.add(telaMatricula);
                telaMatricula.setVisible(true);
                break;
            case 5:
                formCadTurma telaCadTurma = new formCadTurma();
                AreaPrincipal.add(telaCadTurma);
                telaCadTurma.setVisible(true);
                break;
            case 6:
                formCadDisciplina telaCadDisciplina = new formCadDisciplina();
                AreaPrincipal.add(telaCadDisciplina);
                telaCadDisciplina.setVisible(true);
                break;
        }
    }
    
    public void diretoNoCodigo(){
        listaCursos.add(new Curso(1000, 70, "Psicologia", "Ciências Humanas e Sociais"));
        listaCursos.add(new Curso(1001, 50, "Ciência da Computação", "Ciências Exatas e Tecnólogicas"));
        listaCursos.add(new Curso(1002, 60, "Arquitetura e Urbanismo", "Ciências Humanas e Sociais"));
        listaCursos.add(new Curso(1003, 50, "Sistemas de Informação", "Ciências Exatas e Tecnólogicas"));
        listaCursos.add(new Curso(1004, 35, "Zootecnia", "Ciências Agrárias"));
        listaCursos.add(new Curso(1005, 50, "Engenharia de Software", "Ciências Exatas e Tecnólogicas"));
        
        listaAlunos.add(new Aluno(120895810, "Muriel S. da Cruz", listaCursos.get(1), "Vestibular", 2016));
        listaAlunos.add(new Aluno(119854410, "Kétuly da S. Ataídes", listaCursos.get(4), "Vestibular", 2015));
        listaAlunos.add(new Aluno(118341210, "Luara Alves da Silva", listaCursos.get(3), "Vestibular", 2016));
        listaAlunos.add(new Aluno(121999888, "Madianita B. Marioti", listaCursos.get(1), "Portador de Diploma", 1996));
        listaAlunos.add(new Aluno(170777555, "Fora Temer", listaCursos.get(0), "Transferência", 2016));
        
        listaProfessores.add(new Professor(30000, "Madianita B. Marioti", listaCursos.get(1), 40));
        listaProfessores.add(new Professor(44000, "Fabiano Fagundes", listaCursos.get(1), 35));
        listaProfessores.add(new Professor(55000, "Cristina D'Ornellas F. Souza", listaCursos.get(3), 20));
        listaProfessores.add(new Coordenador(12999, "Parcilene F. de Brito", listaCursos.get(1), 40, 6000.00));
        listaProfessores.add(new Coordenador(99999, "Irenides Teixeira", listaCursos.get(0), 40, 3000.00));
        listaProfessores.add(new Professor(77000, "Ibêre Parente", listaCursos.get(4), 40));
        
        listaDisciplinas.add(new Disciplina(1000, 4, "Linguagem de Programação Orientada a Objetos I", listaCursos.get(1)));
        listaDisciplinas.add(new Disciplina(1001, 8, "Eng. de Software I", listaCursos.get(5)));
        listaDisciplinas.add(new Disciplina(1002, 4, "Alimentos e Alimentação", listaCursos.get(4)));
        listaDisciplinas.add(new Disciplina(1003, 4, "Fotografia Aplicada à Psicologia", listaCursos.get(0)));
        listaDisciplinas.add(new Disciplina(1004, 4, "Psicologia do Desenvolvimento I", listaCursos.get(0)));
        listaDisciplinas.add(new Disciplina(1005, 6, "Lógica de Predicados", listaCursos.get(1)));
        listaDisciplinas.add(new Disciplina(1006, 4, "Fundamentos de Sistemas de Informação", listaCursos.get(3)));
        listaDisciplinas.add(new Disciplina(1007, 8, "AutoCAD", listaCursos.get(2)));
        listaDisciplinas.add(new Disciplina(1008, 4, "Estrutura de Dados I", listaCursos.get(1)));
        
        
        
        listaTurmas.add(new Teorica(306, 40, listaDisciplinas.get(1), "2017.1", listaProfessores.get(2), "7M", 201));
        listaTurmas.add(new Pratica(706, 36, listaDisciplinas.get(0), "2017.1", listaProfessores.get(0), "4N", "Labin IV"));
        listaTurmas.add(new Teorica(804, 30, listaDisciplinas.get(3), "2016.2", listaProfessores.get(4), "6N", 225));
        listaTurmas.add(new Pratica(201, 2, listaDisciplinas.get(2), "2017.1", listaProfessores.get(5), "2M", "Curral ULBRA"));
        listaTurmas.add(new Teorica(800, 20, listaDisciplinas.get(4), "2017.1", listaProfessores.get(2), "5M", 202));
        listaTurmas.add(new Teorica(703, 25, listaDisciplinas.get(5), "2017.1", listaProfessores.get(3), "3N", 410));
        listaTurmas.add(new Teorica(303, 25, listaDisciplinas.get(6), "2017.1", listaProfessores.get(1), "5N", 203));
        listaTurmas.add(new Pratica(900, 26, listaDisciplinas.get(7), "2017.1", listaProfessores.get(3), "6M", "Labin IX"));
        listaTurmas.add(new Teorica(806, 30, listaDisciplinas.get(3), "2017.1", listaProfessores.get(4), "6N", 225));
        listaTurmas.add(new Pratica(305, 25, listaDisciplinas.get(8), "2017.1", listaProfessores.get(1), "6N", "Labin V"));
        
        
        
        listaMatriculas.add(new Matricula(listaAlunos.get(0), listaTurmas.get(1)));
        listaMatriculas.add(new Matricula(listaAlunos.get(0), listaTurmas.get(0)));
        listaMatriculas.add(new Matricula(listaAlunos.get(2), listaTurmas.get(0)));
        listaMatriculas.add(new Matricula(listaAlunos.get(2), listaTurmas.get(1)));
            listaTurmas.get(0).setQtAlunos(2);
            listaTurmas.get(1).setQtAlunos(2);
            
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane AreaPrincipal;
    private javax.swing.JButton btnCadAluno;
    private javax.swing.JButton btnCadCurso;
    private javax.swing.JButton btnCadDisciplina;
    private javax.swing.JButton btnCadProfessor;
    private javax.swing.JButton btnCadTurma;
    private javax.swing.JButton btnMatricula;
    private javax.swing.JMenuItem itemMenuCadAluno;
    private javax.swing.JMenuItem itemMenuCadCurso;
    private javax.swing.JMenuItem itemMenuCadDiscilina;
    private javax.swing.JMenuItem itemMenuCadProfessor;
    private javax.swing.JMenuItem itemMenuCadTurma;
    private javax.swing.JMenuItem itemMenuMatrAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuSecAbout;
    private javax.swing.JMenu menuSecCad;
    private javax.swing.JMenu menuSecMatriculas;
    private javax.swing.JMenu menuSecSair;
    // End of variables declaration//GEN-END:variables
}
