/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;
import Classes.Curso;
import javax.swing.JOptionPane;
import static formularios.formPrincipal.listaCursos;
/**
 *
 * @author 120895810
 */

public class formCadCurso extends javax.swing.JInternalFrame {
    Curso cursoGlobal; 
    
    /**
     * Creates new form CadastroCurso
     */
    public formCadCurso() {
        initComponents();
        buttonAltCurso.setEnabled(false);
        buttonExcluir.setEnabled(false);
        tfCGU.setText(""+gerarCodigo());
    }
    static int codigo;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfValorCredito = new javax.swing.JTextField();
        comboBoxAreaConhecimento = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaSaidaCurso = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        tfCGU = new javax.swing.JTextField();
        buttonLimpar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        buttonCadCurso = new javax.swing.JToggleButton();
        buttonPesqCurso = new javax.swing.JButton();
        buttonAltCurso = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        buttonImprimir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro Cursos");
        setPreferredSize(new java.awt.Dimension(800, 660));

        tfNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Nome do Curso:");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Area de Conhecimento:");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Valor do Crédito:");

        tfValorCredito.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        comboBoxAreaConhecimento.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        comboBoxAreaConhecimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Ciências Agrárias", "Ciências Biológicas e da Saúde", "Ciências Exatas e Tecnológicas", "Ciências Humanas e Sociais" }));
        comboBoxAreaConhecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxAreaConhecimentoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jLabel4.setText("Cadastro de Curso ");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jLabel5.setText("Cadastro");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Saída", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        textAreaSaidaCurso.setEditable(false);
        textAreaSaidaCurso.setColumns(20);
        textAreaSaidaCurso.setRows(5);
        jScrollPane1.setViewportView(textAreaSaidaCurso);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Código Curso: ");

        tfCGU.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        buttonLimpar.setBackground(new java.awt.Color(51, 51, 51));
        buttonLimpar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        buttonLimpar.setForeground(new java.awt.Color(255, 255, 255));
        buttonLimpar.setText("Limpar");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dkcl.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");

        buttonCadCurso.setBackground(new java.awt.Color(0, 102, 255));
        buttonCadCurso.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        buttonCadCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesBotoes/Save-32.png"))); // NOI18N
        buttonCadCurso.setText("Cadastrar");
        buttonCadCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadCursoActionPerformed(evt);
            }
        });

        buttonPesqCurso.setBackground(new java.awt.Color(51, 204, 0));
        buttonPesqCurso.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        buttonPesqCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesBotoes/FormatFactorySearch-32.png"))); // NOI18N
        buttonPesqCurso.setText("Pesquisar");
        buttonPesqCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesqCursoActionPerformed(evt);
            }
        });

        buttonAltCurso.setBackground(new java.awt.Color(255, 255, 102));
        buttonAltCurso.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        buttonAltCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesBotoes/FormatFactoryEdit-32.png"))); // NOI18N
        buttonAltCurso.setText("Alterar");
        buttonAltCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAltCursoActionPerformed(evt);
            }
        });

        buttonExcluir.setBackground(new java.awt.Color(255, 51, 51));
        buttonExcluir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        buttonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesBotoes/FormatFactoryDelete-32.png"))); // NOI18N
        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        buttonImprimir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        buttonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesBotoes/FormatFactoryPrint-32.png"))); // NOI18N
        buttonImprimir.setText("Imprimir");
        buttonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonLimpar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(tfValorCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxAreaConhecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(tfCGU, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(buttonCadCurso)
                                    .addGap(18, 18, 18)
                                    .addComponent(buttonPesqCurso)
                                    .addGap(31, 31, 31)
                                    .addComponent(buttonAltCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(buttonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(buttonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonLimpar)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCGU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(comboBoxAreaConhecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(tfValorCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAltCurso)
                    .addComponent(buttonExcluir)
                    .addComponent(buttonImprimir)
                    .addComponent(buttonPesqCurso)
                    .addComponent(buttonCadCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(182, 182, 182))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadCursoActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_buttonCadCursoActionPerformed

    private void comboBoxAreaConhecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxAreaConhecimentoActionPerformed
     
    }//GEN-LAST:event_comboBoxAreaConhecimentoActionPerformed

    private void buttonPesqCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesqCursoActionPerformed
        pesquisar();
    }//GEN-LAST:event_buttonPesqCursoActionPerformed

    private void buttonAltCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAltCursoActionPerformed
        alterar();
    }//GEN-LAST:event_buttonAltCursoActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        limpar();
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        excluir();
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void buttonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImprimirActionPerformed
        imprimirAll();
    }//GEN-LAST:event_buttonImprimirActionPerformed
    
    public Curso existeCurso(String nome, String CGU){
        if (nome.equals("")){
            if (CGU.equals("")){
                return null;
            }
            else{
                for(Curso curso:listaCursos){
                    if(curso.getCodigo() == Integer.parseInt(CGU)){
                        return curso;
                    }
                }
            }
        }
        else{
            for(Curso c:listaCursos){
                if(c.getNome().equals(nome)){
                    return c;
                }
            }
        }
        return null;
    }
    public void cadastrar(){
        cursoGlobal = existeCurso(tfNome.getText(),(tfCGU.getText()));
        if (cursoGlobal == null){
            if(validaDados()){
                cursoGlobal = new Curso(Integer.parseInt(tfCGU.getText()),Double.parseDouble(tfValorCredito.getText()), tfNome.getText(),""+comboBoxAreaConhecimento.getSelectedItem());
                listaCursos.add(cursoGlobal);
                textAreaSaidaCurso.setText(cursoGlobal.toString());
                JOptionPane.showMessageDialog(null,tfNome.getText()+" foi cadastrado com sucesso!");
                tfCGU.setText(Integer.toString(gerarCodigo()));
            }
            else{
                textAreaSaidaCurso.setText("Verifique os dados e tente novamente");
            }
        }
        else{
            textAreaSaidaCurso.setText("Curso já cadastrado ou campos vazios");
        }
    }
    
    public void pesquisar(){
        cursoGlobal = existeCurso(tfNome.getText(),(tfCGU.getText()));
        if (cursoGlobal !=null){
            JOptionPane.showMessageDialog(null, "Curso localizado!");
            textAreaSaidaCurso.setText(cursoGlobal.toString());
            tfCGU.setText(""+cursoGlobal.getCodigo());
            tfNome.setText(cursoGlobal.getNome());
            comboBoxAreaConhecimento.setSelectedItem(cursoGlobal.getAreaConhecimento());
            tfValorCredito.setText(""+cursoGlobal.getValorCredito());
            buttonAltCurso.setEnabled(true);
            buttonExcluir.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Curso NÃO localizado!");
            limpar();
            textAreaSaidaCurso.setText("");
        }
    }
    
    public void alterar(){
        if (validaDados()){
            cursoGlobal.setNome(tfNome.getText());
            cursoGlobal.setCodigo(Integer.parseInt(tfCGU.getText()));
            cursoGlobal.setAreaConhecimento((String)comboBoxAreaConhecimento.getSelectedItem());
            cursoGlobal.setValorCredito(Double.parseDouble(tfValorCredito.getText()));
            textAreaSaidaCurso.setText("Dados alterados com sucesso!\n"+cursoGlobal.toString());
        }
        else{
            textAreaSaidaCurso.setText("Corriga os dados antes de alteralos!");
        }
    }
    public void excluir(){
        String curso = cursoGlobal.getNome();
        listaCursos.remove(cursoGlobal);
        textAreaSaidaCurso.setText("O curso "+curso+" foi removido do sistema!");
        buttonAltCurso.setEnabled(false);
        buttonExcluir.setEnabled(false);
        limpar();
        
    }
    
    public void imprimirAll(){
        textAreaSaidaCurso.setText("");
        for(Curso c: listaCursos){
            textAreaSaidaCurso.append(c.toString()+"\n");
        }
    }
    public void limpar(){
        tfCGU.setText(""+codigo);
        tfNome.setText("");
        tfValorCredito.setText("");
        comboBoxAreaConhecimento.setSelectedIndex(0);
        buttonAltCurso.setEnabled(false);
        buttonExcluir.setEnabled(false);
        buttonCadCurso.setEnabled(true);
    }

    
    public boolean validaDados(){
        if(!(tfCGU.getText().equals("")) && !(tfNome.getText().equals("")) && comboBoxAreaConhecimento.getSelectedIndex()!=0 && !(tfValorCredito.getText().equals(""))){
            return (tfCGU.getText()).matches("[0-9]*");
        } 
        return false;
    }
    public int gerarCodigo(){
        codigo = 1000 + listaCursos.size();
        codigo = codigo + 1;
        return codigo;
    }
        


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAltCurso;
    private javax.swing.JToggleButton buttonCadCurso;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonImprimir;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonPesqCurso;
    private javax.swing.JComboBox<String> comboBoxAreaConhecimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea textAreaSaidaCurso;
    private javax.swing.JTextField tfCGU;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfValorCredito;
    // End of variables declaration//GEN-END:variables
}
