/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;
import Classes.Professor;
import Classes.Coordenador;
import Classes.Curso;
import javax.swing.JOptionPane;
import static formularios.formPrincipal.listaCursos;
import static formularios.formPrincipal.listaProfessores;

/**
 *
 * @author Muriel
 */
public class formCadProfessor extends javax.swing.JInternalFrame {
   Professor profGlobal;
   Coordenador coordGlobal;
    Double valorHoraAula = 100.00;
    
    /**
     * Creates new form CadastroProfessores
     */
    public formCadProfessor() {       
        initComponents();{
        Professor.setValorHoraAula(valorHoraAula);
        tfValorHAula.setText(Double.toString(valorHoraAula));
        tfGratificação.setEnabled(false);
   
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        /**InterfacePrincipal var = new InterfacePrincipal();
        var.preencheCombos(cbxCurso); */
        
        preencheCombos();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CheckBoxCoordenador = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        tfCGU = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfCargaHoraria = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        iconeP = new javax.swing.JLabel();
        tfValorHAula = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaProf = new javax.swing.JTextArea();
        cbxCurso = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        tfGratificação = new javax.swing.JTextField();
        alterarValorHoraAula = new javax.swing.JButton();
        tfSalario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro Professores/Coordenadores");
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(800, 660));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("CGU do Professor: ");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Curso:");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Carga Horaria Semanal:");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Valor da Hora Aula: ");

        CheckBoxCoordenador.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        CheckBoxCoordenador.setText("Coordenador");
        CheckBoxCoordenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxCoordenadorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jLabel6.setText("Cadastro de Professor ");

        tfCGU.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        tfNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        tfCargaHoraria.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        iconeP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dkcl.jpg"))); // NOI18N
        iconeP.setText("jLabel7");
        iconeP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconePMouseClicked(evt);
            }
        });

        tfValorHAula.setEditable(false);
        tfValorHAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorHAulaActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(0, 102, 204));
        btnCadastrar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesBotoes/iconesMicro/Save-32.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnPesquisar.setBackground(new java.awt.Color(0, 204, 0));
        btnPesquisar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesBotoes/iconesMicro/FormatFactorySearch-32.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jLabel8.setText("Cadastro");

        btnAlterar.setBackground(new java.awt.Color(255, 255, 0));
        btnAlterar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesBotoes/iconesMicro/FormatFactoryEdit-32.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(255, 0, 0));
        btnExcluir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesBotoes/iconesMicro/FormatFactoryDelete-32.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnImprimir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconesBotoes/iconesMicro/FormatFactoryPrint-32.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Saida", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N

        textAreaProf.setEditable(false);
        textAreaProf.setColumns(20);
        textAreaProf.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        textAreaProf.setRows(5);
        jScrollPane1.setViewportView(textAreaProf);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );

        cbxCurso.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..." }));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setText("Gratificação:");

        tfGratificação.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        alterarValorHoraAula.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        alterarValorHoraAula.setText("alterar Hora/Aula");
        alterarValorHoraAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarValorHoraAulaActionPerformed(evt);
            }
        });

        tfSalario.setEditable(false);
        tfSalario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setText("Salário:");

        btnLimpar.setBackground(new java.awt.Color(51, 51, 51));
        btnLimpar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addGap(8, 8, 8)
                                .addComponent(tfCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tfCGU, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tfValorHAula, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 88, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(btnCadastrar)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterar)
                .addGap(12, 12, 12)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnImprimir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator6)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iconeP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6))
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CheckBoxCoordenador)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfGratificação, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterarValorHoraAula)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpar)
                            .addComponent(iconeP, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCGU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfValorHAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckBoxCoordenador)
                            .addComponent(jLabel9)
                            .addComponent(tfGratificação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnPesquisar)
                                    .addComponent(btnAlterar)
                                    .addComponent(btnExcluir)
                                    .addComponent(btnImprimir)
                                    .addComponent(btnCadastrar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alterarValorHoraAula)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBoxCoordenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxCoordenadorActionPerformed
        if(CheckBoxCoordenador.isSelected()){
            tfGratificação.setEnabled(true);
        }
        else{
            tfGratificação.setEnabled(false);
        }
    }//GEN-LAST:event_CheckBoxCoordenadorActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        pesquisar();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void tfValorHAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorHAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValorHAulaActionPerformed

    private void alterarValorHoraAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarValorHoraAulaActionPerformed
        double valor = Double.parseDouble(JOptionPane.showInputDialog("Novo valor da hora/aula:"));
        Professor.setValorHoraAula(valor);
        tfValorHAula.setText(Double.toString(valor));
    }//GEN-LAST:event_alterarValorHoraAulaActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        alterar();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        excluir();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        imprimirAll();
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void iconePMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconePMouseClicked
       //InterfacePrincipal var = new InterfacePrincipal();
       // var.setVisible(true);
    }//GEN-LAST:event_iconePMouseClicked

    public Professor existeProf(String nome, String CGU){
        if (CGU.equals("")){
            if (nome.equals("")){
                return null;
            }
            else{
                for(Professor prof:listaProfessores){
                    if(prof.getNome().equals(nome)){
                        return prof;
                    }
                }
            }
        }
        else{
            for(Professor prof:listaProfessores){
                if(prof.getCgu() == Integer.parseInt(CGU)){
                    return prof;
                }
            }
        }
        return null;
    }
    
    public void cadastrar(){
        profGlobal = existeProf(tfNome.getText(),(tfCGU.getText()));
        if (profGlobal == null){
            if(validaDados()){
                if((existeProf("",tfCGU.getText())) == null){ /** REDUNDANTE */
                    if(CheckBoxCoordenador.isSelected()){
                        profGlobal = new Coordenador(Long.parseLong(tfCGU.getText()),tfNome.getText(),listaCursos.get(cbxCurso.getSelectedIndex()-1),Integer.parseInt(tfCargaHoraria.getText()),Double.parseDouble(tfGratificação.getText()));
                        listaProfessores.add(profGlobal);
                        textAreaProf.setText(profGlobal.toString());
                    }
                    else{
                        profGlobal = new Professor(Long.parseLong(tfCGU.getText()),tfNome.getText(),listaCursos.get(cbxCurso.getSelectedIndex()-1),Integer.parseInt(tfCargaHoraria.getText()));
                        listaProfessores.add(profGlobal);
                        textAreaProf.setText(profGlobal.toString());
                    }
                JOptionPane.showMessageDialog(null,tfNome.getText()+" foi cadastrado com sucesso!");
                }
               /** else{
                    textAreaAluno.setText("Essa CGU está vinculada a um aluno");
                } */
            }
            else{
                textAreaProf.setText("Verifique os dados e tente novamente");
            }
            tfSalario.setText(""+profGlobal.calcularSalario()+"R$");
        }
        else{
            textAreaProf.setText("Servidor já cadastrado ou campos vazios");
        }
        
    }
    
    public void pesquisar(){
        profGlobal = existeProf(tfNome.getText(),(tfCGU.getText()));
        if (profGlobal !=null){
            limpar();
            textAreaProf.setText("Professor localizado!\n"+ profGlobal.toString());
            tfCGU.setText(""+profGlobal.getCgu());
            tfNome.setText(profGlobal.getNome());
            cbxCurso.setSelectedItem(profGlobal.getCurso().getNome());
            tfCargaHoraria.setText(""+profGlobal.getCargaHoraria());
            tfSalario.setText(""+profGlobal.calcularSalario()+"R$");
            if(profGlobal instanceof Coordenador){
                coordGlobal = (Coordenador) profGlobal;
                tfGratificação.setEnabled(true);
                tfGratificação.setText(""+coordGlobal.getGratificacao());
                CheckBoxCoordenador.setSelected(true);
            }
            else{
                tfGratificação.setEnabled(false);
                CheckBoxCoordenador.setSelected(false);
            }
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
            CheckBoxCoordenador.setEnabled(false);
            btnCadastrar.setEnabled(false);
        }
        else{
            textAreaProf.setText("Professor/Coordenador NÃO localizado!");
        }  
    }
    
    public void alterar(){
        if (validaDados()){
            profGlobal.setNome(tfNome.getText());
            profGlobal.setCgu(Integer.parseInt(tfCGU.getText()));
            profGlobal.setCurso(listaCursos.get(cbxCurso.getSelectedIndex()-1));
            profGlobal.setCargaHoraria(Integer.parseInt(tfCargaHoraria.getText()));
            if(CheckBoxCoordenador.isSelected()){
                coordGlobal = (Coordenador) profGlobal;
                coordGlobal.setGratificacao(Double.parseDouble(tfGratificação.getText()));
            }
            textAreaProf.setText("Dados alterados com sucesso!\n"+profGlobal.toString());
        }
        else{
            textAreaProf.setText("Corriga os dados antes de altera-los!"); //não digite uma CGU cadastrada
        }
        limpar();
    }
    
    public void excluir(){
        String prof = profGlobal.getNome();
        listaProfessores.remove(profGlobal);
        textAreaProf.setText("O professor/Coordenador "+prof+" foi removido do sistema!");
        limpar();
        
    }
    
    public void imprimirAll(){
        textAreaProf.setText("CGU - nome do professor - nome do curso - salario - tipo (professor ou coordenador)\n\n");
        for(Professor p: listaProfessores){
            textAreaProf.append(""+p.getCgu()+" - "+p.getNome()+" - " + p.getCurso().getNome() + " - "+p.calcularSalario()+"R$ - ");
            if(p.getClass().getName().equals("Classes.Coordenador")){
                textAreaProf.append("Coordenador \n");
            }
            else{
                textAreaProf.append("Professor \n");
            }
        }
    }
    
    public void limpar(){
        tfCGU.setText("");
        tfNome.setText("");
        cbxCurso.setSelectedIndex(0);
        CheckBoxCoordenador.setSelected(false);
        tfGratificação.setText("");
        tfGratificação.setEnabled(false);
        tfCargaHoraria.setText("");
        tfSalario.setText("");
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCadastrar.setEnabled(true);
        CheckBoxCoordenador.setEnabled(true);
    }
    public boolean validaDados(){
        if(!(tfCGU.getText().equals("")) && cbxCurso.getSelectedIndex()!=0 &&!(tfNome.getText().equals("")) && !(tfCargaHoraria.equals(""))){
            if ((tfCGU.getText()).matches("[0-9]*")){
                return (true);
            }
        } 
        return false;
    }
    public void preencheCombos(){
        for (Curso c: listaCursos){
            cbxCurso.addItem(c.getNome());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxCoordenador;
    private javax.swing.JButton alterarValorHoraAula;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cbxCurso;
    private javax.swing.JLabel iconeP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextArea textAreaProf;
    private javax.swing.JTextField tfCGU;
    private javax.swing.JTextField tfCargaHoraria;
    private javax.swing.JTextField tfGratificação;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfSalario;
    private javax.swing.JTextField tfValorHAula;
    // End of variables declaration//GEN-END:variables
}
